#define UBO_BINDING_APP 0
#define UBO_BINDING_SCENE 1
#define UBO_BINDING_CAMERA 2
#define UBO_BINDING_MODEL 3
#define UBO_BINDING_SHADOW 4
#define UBO_BINDING_LIGHTS 5


#define UBO_BINDING_DIRECTIONAL_LIGHT 11
#define UBO_BINDING_SPOT_LIGHT 12
#define UBO_BINDING_POINT_LIGHT 13